### ISSUE TITLE
setting global theme: costs vs. benefits

### ISSUE THREAD

**Issue by grasshoppermouse** [stan-dev/bayesplot#117] opened 2017-09-24 15:06 UTC
It took me a few minutes to discover why all the figures in our paper changed. Answer: one of the co-authors added some code that used bayesplot. It took another few minutes of googling to figure out how to fix that. Not a huge deal, but it's nice when loading and using a package that there are as few unintended side effects as possible. On the other hand, there are benefits if you are only using bayesplot and/or like the theme. For me, the (small) costs outweigh the benefits.

Thoughts on the cost/benefit tradeoff of setting the global ggplot theme?

**Comment by jgabry** [comment] 2017-09-24 15:38
Thanks for the comment. The bayesplot package didn't used to set the ggplot theme when it was loaded. It used to just hardcode a theme for each plot without affecting the rest of ggplot2, but that was actually changed in a recent release in order to make it easier to change the theme of bayesplot plots (https://github.com/stan-dev/bayesplot/issues/87). That is, `ggplot2::theme_set` didn't used to affect bayesplot plots but with this change you can now use it just like you would with regular ggplot2. 

You can see from the discussion at https://github.com/stan-dev/bayesplot/issues/87 that I was hesitant to do this because it changes the ggplot theme for all plots when bayesplot is loaded. But I was persuaded that since there's a precedent for this behavior in other plotting packages, the benefits outweighed the costs. That said, I can totally understand that for some people the costs outweigh the benefits.

**Comment by grasshoppermouse** [comment] 2017-09-24 15:58
OK, thanks. I did search for a previous issue but missed that one. I also hate that cowplot changes the global theme too, as apparently do some other folks:

https://stackoverflow.com/questions/41096293/cowplot-made-ggplot2-theme-disappear-how-to-see-current-ggplot2-theme-and-res

So now I avoid loading that package if at all possible. I guess a solution is to use bayesplot::

In any case, thanks for the package!

**Comment by jgabry** [comment] 2017-09-24 16:15
Yeah I'm also not a big fan of changing the theme when loading the package.
But I also don't like hardcoding the bayesplot theme for each plot. And I
clearly haven't been able to come up with a satisfactory resolution to that
conflict!

That said, when writing R scripts that should be reproducible, I think it's
good practice to explicitly set the plotting theme with theme_set after
loading packages. That does sidestep this problem as well as making it
clear to the reader what theme is being used.

Alternatively, like you suggested, bayesplot::fun should work fine.

**Comment by jgabry** [comment] 2017-09-24 16:17
@tjmahr What's your take on this issue?

**Comment by tjmahr** [comment] 2017-09-24 16:52
I don’t think bayesplot should change the global theme. I wish we could scope a theme to be the default for theme code in a package but there doesn’t seem to be a way to do that. I think adding a + theme_bayesplot() to every ggplot call is not too much of a burden. We could write a wrapper over ggplot() that calls ggplot() and adds the theme too.

**Comment by tjmahr** [comment] 2017-09-26 01:46
Looking back at the issue by @gavinsimpson, #87...

We don't want to be impolite and mess with the global settings. I went four years of using ggplot2 without ever having to use `theme_set()`, but I had to learn it in order to use bayesplot. But we want to spare users the tedium of having to overwrite theme on every bayesplot theme.

What if we do `theme_set_bayesplot()`? On load, it's the bayesplot default. But the user can override it with `theme_set_bayesplot()`?

**Comment by gavinsimpson** [comment] 2017-09-29 19:58
@tjmahr I think that is what I had suggested in #87 (although I don't follow why this is `theme_set_bayesplot()` and not `theme_set(theme_bayesplot())`?). A popular package that uses `.onAttach()` to set the theme globally in the workspace is **cowplot**. It used to frustrate me as a user that cowplot changed the default as I was really only interested in its layout functions. Given the triviality of changing the theme back to what I want (I use `theme_bw()` in general), and the fact that users of **bayesplot** are doing so for the plots (which the developers have given nice thought to) I don't see it as too much of an intrusion to set the theme globally.

Importantly, however, (re)setting the theme should be done via standard functions, e.g. `theme_set(theme_foo())`.

Whether you want to automatically set this depends on who you want to frustrate most; existing users who now find all their plots change if you don't automatically set the theme to the bayesplot default, or new users that never saw the hard-coded bayesplot theme and don't know why all their ggplot plots now look different.

I'm happy either way.

**Comment by tjmahr** [comment] 2017-09-29 20:10
I am proposing that bayesplot have its own `theme_set` and `theme_get` functions.

Basic idea:

* In bayesplot plotting functions, use `theme_get_bayesplot()` to get the current theme for bayesplot functions.
* On package load, call `theme_set_bayesplot(theme_bayesplot())` to set the theme for bayesplot functions to the default. _The user's current global ggplot2 theme is unchanged._
* If the user wants to override the theme for bayesplot plots, they can send a theme to `theme_set_bayesplot()`. _The user doesn't have to re-theme every plot from bayesplot_.

This solves both issues:

1. We don't mess with the global plotting theme on package load.
2. Users can set a theme to override the default bayesplot look.

**Comment by gavinsimpson** [comment] 2017-09-29 20:21
@tjmahr Hmmm. Doesn't that make it harder to discover what's going on and how to turn it off?

But intriguing suggestion; are you proposing to have all plots in bayesplot have `+ bayesplot_theme_obj` (or some such named theme object), with that theme *object* controlled via `theme_set_bayesplot()`.

That's certainly different and will likely satisfy everyone. Interested to see how this progresses.

**Comment by tjmahr** [comment] 2017-09-29 21:47
Yes, that’s another way of describing it. And I can make it discoverable by adjusting the start-up message.

I would like to others weigh in with any unforeseen problems with this idea.

**Comment by jgabry** [comment] 2018-03-19 17:18
This issue is a bit old now but I do think this is something we should revisit. Over at https://github.com/stan-dev/rstanarm/issues/257 I proposed something similar to @tjmahr's proposal here. I'm still not sure what the best thing to do is, as all of the options seem to have downsides, but let's get this conversation started again so we can settle on something soon.

**Comment by malcolmbarrett** [comment] 2018-03-20 03:06
Oh yes, what @tjmahr is describing is similar to what I imagined based on @jgabry's comment here  stan-dev/rstanarm#258. I also shared some potential code for it there. I think it's any interesting solution and, like I mentioned over there, I think it would be easy to make it play nice with existing changes to the default theme set by a user by comparing whatever the theme is to `theme_gray()` for any differences (e.g. could have `bayes_theme_set()` check if `theme_get()` is different from `theme_gray()` and if so just use the user's default but otherwise use the default bayesplot theme).

I do, though, agree that all of these ways of dealing with it have their downsides. There's also something to be said about simply including a theme and not having it be defaulted anywhere, although it's probably late in the game for you all for something like that.

Anyway, let me know if I can help.

**Comment by jgabry** [comment] 2018-04-28 17:45
@malcolmbarrett If you’re interested in making a PR for this we’d be happy to have it. @tjmahr or I will definitely get to this eventually regardless, but you put a lot of work into that rstanarm PR that’s obviated by this change to bayesplot and I wanted to give you the opportunity to contribute a PR that’s likely to get merged! No worries if you don’t have the time, but if you’re up for it that would be great!

**Comment by malcolmbarrett** [comment] 2018-04-28 19:57
Yes, I can give this a shot next week. The skeleton I posted looks like a good approach? I would also really like to embed a little hierarchy, e.g. if the user has set bayes_theme_set() to something other than the default, use that, then check against ggplot2::theme_get() to see if different than theme_grey(), otherwise use the default bayes theme. That way the user can just use ggplot2::theme_set() without having to think about it (or learn a new approach) but someone who is really just focused on bayesplot can specify both (or none, just using defaults) if desired

**Comment by tjmahr** [comment] 2018-04-29 02:00
Re bayesplot getting the theme from ggplot2: My concern here is that 

library(bayesplot)
library(ggplot2)

should *not* set the theme of bayesplot to theme_grey(). 

I would prefer to just have a bayesplot get its own bayesplot_theme_get() and bayesplot_theme_set()

**Comment by malcolmbarrett** [comment] 2018-04-29 02:04
Yes, my thinking is that it would only change to whatevrer is in theme_get() if the user has done theme_set(), which is to say that if it's theme_grey, it would not override the bayesplot theme.

**Comment by jgabry** [comment] 2018-04-29 04:54
I agree, I think having `bayesplot_theme_[sg]et` (and I guess also `bayesplot_theme_update`) would be great.

**Closed** 2018-06-09 18:23 UTC
